/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#0F1511',
        'on-background': '#DEE4DE',
        surface: '#0F1511',
        'on-surface': '#DEE4DE',
        'on-surface-variant': '#BCCAC0',
        'surface-container-lowest': '#0A0F0C',
        'surface-container-low': '#171D19',
        'surface-container': '#1B211D',
        'surface-container-high': '#252B28',
        'surface-container-highest': '#303632',
        'surface-variant': '#303632',
        'outline-variant': '#3D4A42',
        outline: '#87948B',
        primary: '#68DBA9',
        primaryHover: '#52C694',
        primarySoft: '#103226',
        primaryFixed: '#85F8C4',
        'primary-container': '#25A475',
        'on-primary': '#003825',
        'on-primary-container': '#00311F',
        secondary: '#BCCAC0',
        'secondary-container': '#494949',
        secondaryContainer: '#494949',
        tertiary: '#FFB3AE',
        'tertiary-container': '#DD706B',
        canvas: '#0F1511',
        ink: '#DEE4DE',
        surfaceLow: '#171D19',
        surfaceMid: '#1B211D',
        surfaceHigh: '#252B28',
        surfaceHighest: '#303632',
        slateLine: '#3D4A42',
        danger: '#FFB4AB',
        dangerSoft: '#3A1518',
        error: '#FFB4AB',
        'error-container': '#93000A',
        success: '#68DBA9',
        successSoft: '#103226',
        warning: '#FFB3AE',
        warningSoft: '#3B2523',
      },
      fontFamily: {
        sans: ['Inter', '"Noto Sans Devanagari"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        display: ['Inter', '"Noto Sans Devanagari"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      boxShadow: {
        panel: '0 18px 48px rgba(0, 0, 0, 0.28)',
        elevated: '0 24px 70px rgba(0, 0, 0, 0.46)',
      },
    },
  },
  plugins: [],
};
